---
title: "CP2_Y1_viability_category_1+2"
output:
  pdf_document: default
  html_document: default
date: "2026-08-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```


```{r}
library(tidyverse)
library(ggplot2)
#library(ggbreak) 
```


```{r}
CP2_Y1 <- read.csv("../output/CP2_Y1_w_elev.csv") %>%
  filter(!(Pop == "WL1" & Rep == 14)) #filter WL1 rep14, because there is no seeds in WL1 rep14 but we have marked it in the spreadsheet; without filter, the NA will be include in the SE and cause all the reps of WL1 become NA
```

#viability across elevation analysis
```{r}
rep_sum_12 <- CP2_Y1 %>%
  group_by (Pop, Elev_m, Rep) %>% #group seeds data by population, elevation and replicates
  summarise (
    trials = sum (!is.na(Updated_viability_cat)), #count how many seeds we have tested in each replicate and remove the cell with NA data in the Updated_viability_cat (some rows are empty seed coat or like WL1 rep14 is an empty envelope)
    events = sum (Updated_viability_cat %in% c(1,2), na.rm = TRUE), #count how many seeds are considered as viable (category 1)
    .groups = "drop"
  ) %>%
  mutate (proportion = events/trials) #calculate viable proportion of each replicate

pop_sum_12 <- rep_sum_12 %>%
  group_by (Pop, Elev_m) %>% #group each replicate data by population and elevation
  summarise(
    n_reps = n(), #count number of replicates of each population
    mean_proportion = mean (proportion, na.rm = TRUE), #calculate mean proportion viable across replicates
    SE = sd(proportion, na.rm = TRUE)/sqrt(n()), #calculate SE of mean viability
    .groups = "drop"
  )
print(pop_sum_12)
```

```{r}
glm_12 <- glm( #fit a binomial generalized linear model
  cbind(events, trials - events) ~ Elev_m, #model viable and non-viable seeds count as a function of population
  family= binomial, #use binomial distribution
  data = rep_sum_12
)
anova(glm_12, test = "Chisq")

prediction_12 <- data.frame( #create a prediction dataset containing one row for each population
  Elev_m = seq(
    min(rep_sum_12$Elev_m),
    max(rep_sum_12$Elev_m),
    length.out = 100
  )
)
prediction_12$predicted <- predict( #calculate predicted viability for each elevation
  glm_12, #use fitted binomial glm
  newdata = prediction_12, #use predicted new elevation data
  type = "response" #return predicted viability data
)

print(summary(glm_12))
```

```{r}
figure_12 <- ggplot(pop_sum_12, aes (x = Elev_m, y = mean_proportion)) + #create a ggplot use population level summary data with x-axis in elevation by meter and y-axis by mean proportion of viable
  geom_line( #add binomial glm trendline by using new prediction data
    data = prediction_12,
    aes(x = Elev_m, y = predicted, group = 1), #plot predicted viability across elevation
    linewidth = 1, color = "red"
  ) +
  geom_point(aes(x = case_when(Pop == "WL3" ~ Elev_m - 50, Pop == "YOSE1" ~ Elev_m + 50, TRUE ~ Elev_m)), size = 2) + #each populations' mean proportion of viable
  geom_errorbar( #add SE bar
    aes(x = case_when(Pop == "WL3" ~ Elev_m - 50, Pop == "YOSE1" ~ Elev_m + 50, TRUE ~ Elev_m),
      ymin= mean_proportion - SE,
      ymax = mean_proportion + SE
    ),
    width = 20
  ) +
  geom_text(
  aes(
    x = Elev_m + case_when(
      Pop == "BH"    ~ 0,
      Pop == "DPR"   ~ 0,
      Pop == "IH"    ~ 0,
      Pop == "LV2"   ~ 0,
      Pop == "SC"    ~ 0,
      Pop == "SQ3"   ~ 0,
      Pop == "TM2"   ~ 0,
      Pop == "WL1"   ~ 0,
      Pop == "WL2"   ~ 0,
      Pop == "WL3"   ~ -50,
      Pop == "YOSE1" ~ 50,
      TRUE ~ 0
    ),
    y = mean_proportion + case_when(
      Pop == "BH"    ~ 0.07,
      Pop == "DPR"   ~ 0.04,
      Pop == "IH"    ~ 0.07,
      Pop == "LV2"   ~ 0.06,
      Pop == "SC"    ~ 0.06,
      Pop == "SQ3"   ~ 0.08,
      Pop == "TM2"   ~ 0.05,
      Pop == "WL1"   ~ 0.07,
      Pop == "WL2"   ~ 0.07,
      Pop == "WL3"   ~ 0.06,
      Pop == "YOSE1" ~ 0.07,
      TRUE ~ 0
    ),
    label = Pop
  ),
  size = 2.5
) + #label each point with its population name
  scale_x_continuous(limits = c(350, 2550), n.break = 15) +
  scale_y_continuous(expand = c(0, 0.05)) +
  theme_classic() + #use classic ggplot theme
  theme(text=element_text(size=10), axis.text.x = element_text(hjust = 1)) +
  labs ( #add labels for x-axis and y-axis
    x = "Elevation (m)",
    y = "Proportion Viable"
  ) 
print(figure_12)
```

#viability across geographical distance
```{r}
distance <- read.csv("../output/CP2_Y1_sites_w_distance_elev_diff.csv")
```

```{r}
pop_sum_12 <- pop_sum_12 %>%
  left_join (distance %>% select (distance_km, Pop), by = "Pop") #join distance with population level data

rep_sum_12 <- rep_sum_12 %>%
  left_join(distance %>% select (distance_km, Pop), by = "Pop") #join distance with replicate level data
```

```{r}
glm_distance <- glm( #fit a binomial generalized linear model
  cbind(events, trials - events) ~ distance_km, #model viable and non-viable seeds count as a function of distance
  family = binomial, #use binomial distribution
  data = rep_sum_12 #use replicate level data (because the data has events and trials but the population level data does not)
)

prediction_distance <- data.frame( #create a prediction dataset for geographic distance
  distance_km = seq(
    min(rep_sum_12$distance_km), #start from the shortest to longest geographic distance
    max(rep_sum_12$distance_km),
    length.out = 100 #generate 100 equally spaced distance values
  )
)

prediction_distance$predicted <- predict( #calculate predicted viability across geographic distance
  glm_distance, #use the fitted binomial glm
  newdata = prediction_distance, #predict viability for the new distance values
  type = "response" #return predicted proportions
)

print(summary(glm_distance))
anova(glm_distance, test = "Chisq")
```

```{r}
figuer_distance <- ggplot ( #create a plot of population mean viability against geographic distance
  pop_sum_12, aes (x = distance_km, y = mean_proportion)
) + 
  geom_line(
  data = prediction_distance,
  aes(
    x = distance_km,
    y = predicted
  ),
  linewidth = 1,
  color = "red" #add the fitted binomial glm prediction line
) +
  geom_point(size = 2.5) + #plot the mean proportion of viable seeds for each population
  geom_errorbar( #add SE bar
    aes(
      ymin= mean_proportion - SE,
      ymax = mean_proportion + SE
    ),
    width = 3
  ) +
  #geom_text (aes (label = Pop), vjust = -6.1, size = 3) + #label each point with its population name
  geom_text(
  aes(
    x = distance_km + case_when(
      Pop == "BH"    ~ 0,
      Pop == "DPR"   ~ 0,
      Pop == "IH"    ~ 0,
      Pop == "LV2"   ~ 0,
      Pop == "SC"    ~ 0,
      Pop == "SQ3"   ~ 0,
      Pop == "TM2"   ~ 0,
      Pop == "WL1"   ~ 0,
      Pop == "WL2"   ~ 0,
      Pop == "WL3"   ~ 0,
      Pop == "YOSE1" ~ 0,
      TRUE ~ 0
    ),
    y = mean_proportion + case_when(
      Pop == "BH"    ~ 0.07,
      Pop == "DPR"   ~ 0.04,
      Pop == "IH"    ~ 0.07,
      Pop == "LV2"   ~ 0.06,
      Pop == "SC"    ~ 0.06,
      Pop == "SQ3"   ~ 0.08,
      Pop == "TM2"   ~ 0.05,
      Pop == "WL1"   ~ 0.06,
      Pop == "WL2"   ~ 0.07,
      Pop == "WL3"   ~ 0.06,
      Pop == "YOSE1" ~ 0.07,
      TRUE ~ 0
    ),
    label = Pop
  ),
  size = 2.5
) +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(expand = c(0, 0.05)) +
  theme(text=element_text(size=10), axis.text.x = element_text(angle = 45,  hjust = 1)) +
  theme_classic() + #use classic ggplot theme
  labs ( #add labels for x-axis and y-axis
    x = "Geographic Distance from CP2 (km)",
    y = "Proportion Viable"
  )
print(figuer_distance)
```

#viability across climate distance
```{r}
climate_distance <- read.csv("../output/CP2_Climate_Distance.csv")
```

```{r}
gowers_recent <- climate_distance %>%
  filter(timeframe == "Recent")

gowers_historic <- climate_distance %>%
  filter(timeframe == "Historic")
```

```{r}
rep_sum_recent <- rep_sum_12 %>%
  left_join(
    gowers_recent %>%
      select(pop, Gowers_Dist),
    by = c("Pop" = "pop")
  )

rep_sum_historic <- rep_sum_12 %>%
  left_join(
    gowers_historic %>%
      select(pop, Gowers_Dist),
    by = c("Pop" = "pop")
  )
```

```{r}
glm_climate_recent <- glm( #fit a binomial generalized linear model
  cbind(events, trials - events) ~ Gowers_Dist, #model viable and non-viable seeds count as a function of distance
  family = binomial, #use binomial distribution
  data = rep_sum_recent #use replicate level data (because the data has events and trials but the population level data does not)
)

glm_climate_historic <- glm(
  cbind(events, trials - events) ~ Gowers_Dist,
  family = binomial,
  data = rep_sum_historic
)

print(summary(glm_climate_recent))
print(summary(glm_climate_historic))
anova(glm_climate_recent, test = "Chisq")
anova(glm_climate_historic, test = "Chisq")
```

```{r}
prediction_climate_recent <- data.frame( #create a prediction dataset for geographic distance
  Gowers_Dist = seq(
    min(rep_sum_recent$Gowers_Dist), #start from the shortest to longest geographic distance
    max(rep_sum_recent$Gowers_Dist),
    length.out = 100 #generate 100 equally spaced distance values
  )
)
prediction_climate_recent$predicted <- predict( #calculate predicted viability across geographic distance
  glm_climate_recent, #use the fitted binomial glm
  newdata = prediction_climate_recent, #predict viability for the new distance values
  type = "response" #return predicted proportions
)

prediction_climate_historic <- data.frame( #create a prediction dataset for geographic distance
  Gowers_Dist = seq(
    min(rep_sum_historic$Gowers_Dist), #start from the shortest to longest geographic distance
    max(rep_sum_historic$Gowers_Dist),
    length.out = 100 #generate 100 equally spaced distance values
  )
)
prediction_climate_historic$predicted <- predict( #calculate predicted viability across geographic distance
  glm_climate_historic, #use the fitted binomial glm
  newdata = prediction_climate_historic, #predict viability for the new distance values
  type = "response" #return predicted proportions
)
```

```{r}
pop_recent <- rep_sum_recent %>%
  group_by(Pop, Gowers_Dist) %>%
  summarise(
    mean_proportion = mean(proportion),
    SE = sd(proportion)/sqrt(n()),
    .groups = "drop"
  )

pop_historic <- rep_sum_historic %>%
  group_by(Pop, Gowers_Dist) %>%
  summarise(
    mean_proportion = mean(proportion),
    SE = sd(proportion)/sqrt(n()),
    .groups = "drop"
  )
```

```{r}
ggplot(pop_recent, aes(x = Gowers_Dist, y = mean_proportion)) +
  geom_line(data = prediction_climate_recent, aes(x = Gowers_Dist, y = predicted), inherit.aes = FALSE, color = "red", linewidth = 1) +
  geom_point(size = 2) +
  geom_errorbar(
    aes(ymin= mean_proportion - SE, ymax = mean_proportion + SE), width = 0.01) +
  #geom_text(aes(label = Pop, vjust = -6), size = 3) +
  geom_text(
  aes(
    x = Gowers_Dist + case_when(
      Pop == "BH"    ~ 0,
      Pop == "DPR"   ~ 0,
      Pop == "IH"    ~ 0,
      Pop == "LV2"   ~ 0,
      Pop == "SC"    ~ 0,
      Pop == "SQ3"   ~ 0,
      Pop == "TM2"   ~ 0,
      Pop == "WL1"   ~ 0,
      Pop == "WL2"   ~ 0,
      Pop == "WL3"   ~ 0,
      Pop == "YOSE1" ~ 0,
      TRUE ~ 0
    ),
    y = mean_proportion + case_when(
      Pop == "BH"    ~ 0.065,
      Pop == "DPR"   ~ 0.04,
      Pop == "IH"    ~ 0.07,
      Pop == "LV2"   ~ 0.06,
      Pop == "SC"    ~ 0.06,
      Pop == "SQ3"   ~ 0.08,
      Pop == "TM2"   ~ 0.05,
      Pop == "WL1"   ~ 0.06,
      Pop == "WL2"   ~ 0.07,
      Pop == "WL3"   ~ 0.06,
      Pop == "YOSE1" ~ 0.07,
      TRUE ~ 0
    ),
    label = Pop
  ),
  size = 2.5
) +
  scale_x_continuous(n.breaks = 7) +
  scale_y_continuous(expand = c(0, 0.05)) +
  theme_classic() +
  labs(x = "Gower Climate Distance from CP2 (1995-2025)", y = "Proportion Viable")
```

```{r}
ggplot(pop_historic, aes (x = Gowers_Dist, y = mean_proportion)) +
  geom_point(size = 2) +
  geom_errorbar(
    aes(ymin = mean_proportion - SE, ymax = mean_proportion + SE), width = 0.01) +
  geom_text(aes(label = Pop, vjust = -5.8), size = 3) +
  geom_line(data = prediction_climate_historic, aes(x = Gowers_Dist, y = predicted), inherit.aes = FALSE, color = "red", linewidth = 1) +
  scale_x_continuous(n.breaks = 7) +
  scale_y_continuous(expand = c(0, 0.05)) +
  theme_classic() +
  labs(x = "Gower Climate Distance from CP2 (1965-1994)", y = "Proportion Viable")
```


#environmental variability by population (temperature + precipitation seasonality)
```{r}
all_clim <- read.csv("../output/WtrYr_Clim_2025NoOct.csv")
```

```{r}
recent_vari <- all_clim %>%
  filter(timeframe == "recent", year >= 1995, year <= 2025, Season == "Water Year", pop != "CP2_garden") %>%
  group_by (pop, Elev_class, Elev_m, Latitude, Longitude) %>%
  summarise(temp_seasonality_sd = sd(temp_seasonality, na.rm = TRUE),
            ppt_seasonality_sd = sd(ppt_seasonality, na.rm = TRUE),
            .groups = "drop")
recent_vari_scaled <- recent_vari %>%
  mutate(across(ends_with("_sd"), ~(.x - min(.x, na.rm = TRUE))/(max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)), .names = "{.col}_scaled"))
recent_vari_scaled <- recent_vari_scaled %>%
  rowwise() %>%
  mutate(
    envi_vari = mean(
      c_across(ends_with("_sd_scaled")),
      na.rm = TRUE
    )
  ) %>%
  ungroup() %>%
  mutate(timeframe = "Recent")
recent_envi_vari <- recent_vari_scaled %>%
  select(pop, Elev_class, Elev_m, Latitude, Longitude, timeframe, envi_vari) %>%
  arrange(envi_vari)

historic_vari <- all_clim %>%
  filter(timeframe == "historic", year >= 1965, year <= 1994, Season == "Water Year", pop != "CP2_garden") %>%
  group_by (pop, Elev_class, Elev_m, Latitude, Longitude) %>%
  summarise(temp_seasonality_sd = sd(temp_seasonality, na.rm = TRUE),
            ppt_seasonality_sd = sd(ppt_seasonality, na.rm = TRUE),
            .groups = "drop")
historic_vari_scaled <- historic_vari %>%
  mutate(across(ends_with("_sd"), ~(.x - min(.x, na.rm = TRUE))/(max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)), .names = "{.col}_scaled"))
historic_vari_scaled <- historic_vari_scaled %>%
  rowwise() %>%
  mutate(
    envi_vari = mean(
      c_across(ends_with("_sd_scaled")),
      na.rm = TRUE
    )
  ) %>%
  ungroup() %>%
  mutate(timeframe = "Historic")
historic_envi_vari <- historic_vari_scaled %>%
  select(pop, Elev_class, Elev_m, Latitude, Longitude, timeframe, envi_vari) %>%
  arrange(envi_vari)

all_envi_vari <- bind_rows(recent_envi_vari, historic_envi_vari)
#write_csv(all_envi_vari, "../output/CP2_Environmental_Variability.csv")
```

```{r}
envi_vari_figure<-all_envi_vari %>%
  ggplot(aes(x = fct_reorder(pop, Elev_m), y = envi_vari, fill = Elev_m)) +
  geom_col(width = 0.8) +
  scale_fill_gradient(low = "#F5A540", high = "#0043F0") +
  facet_wrap(~timeframe) +
  theme_classic() +
  scale_y_continuous(expand = c(0, 0.01))+
  labs(x = "Population", y = "Environmental Variability", fill = "Elevation (m)") +
  theme(text = element_text (size = 18), axis.text.x = element_text(size = 9, angle = 45, hjust = 1))
print(envi_vari_figure)
```

#viability across environmental variability (temperature + precipitation seasonality)
```{r}
rep_sum_envi_recent <- rep_sum_12 %>%
  left_join(recent_envi_vari %>% select(pop, envi_vari), by = c("Pop" = "pop"))
rep_sum_envi_historic <- rep_sum_12 %>%
  left_join(historic_envi_vari %>% select(pop, envi_vari), by = c("Pop" = "pop"))

glm_envi_recent <- glm(
  cbind(events, trials - events) ~ envi_vari,
  family = binomial,
  data = rep_sum_envi_recent
)
glm_envi_historic <- glm(
  cbind (events, trials - events) ~envi_vari,
  family = binomial,
  data = rep_sum_envi_historic
)

anova(glm_envi_recent, test = "Chisq")
anova(glm_envi_historic, test = "Chisq")

print(summary(glm_envi_recent))
print(summary(glm_envi_historic))
```

```{r}
prediction_envi_recent <- data.frame(
  envi_vari = seq(
    min(rep_sum_envi_recent$envi_vari),
    max(rep_sum_envi_recent$envi_vari),
    length.out=100
  )
)
prediction_envi_recent$predicted <- predict(
  glm_envi_recent,
  newdata=prediction_envi_recent,
  type = "response"
)

prediction_envi_historic <- data.frame(
  envi_vari = seq(
    min(rep_sum_envi_historic$envi_vari),
    max(rep_sum_envi_historic$envi_vari),
    length.out=100
  )
)
prediction_envi_historic$predicted <- predict(
  glm_envi_historic,
  newdata=prediction_envi_historic,
  type = "response"
)
```

```{r}
pop_envi_recent <- pop_sum_12 %>%
  left_join(recent_envi_vari %>% select(pop, envi_vari), by = c ("Pop" = "pop"))
pop_envi_historic <- pop_sum_12 %>%
  left_join(historic_envi_vari %>% select(pop, envi_vari), by = c("Pop" = "pop"))
```

```{r}
figure_envi_recent <- ggplot(pop_envi_recent, aes (x = envi_vari, y = mean_proportion)) +
  geom_line(data = prediction_envi_recent, aes(x = envi_vari, y = predicted), inherit.aes = FALSE, color = "red", linewidth = 1) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin= mean_proportion - SE, ymax = mean_proportion + SE), width = 0.01) +
  #geom_text(aes(label = Pop), vjust = -7.5, size = 2.5) +
   geom_text(
  aes(
    x = envi_vari + case_when(
      Pop == "BH"    ~ 0,
      Pop == "DPR"   ~ 0,
      Pop == "IH"    ~ 0,
      Pop == "LV2"   ~ 0,
      Pop == "SC"    ~ 0,
      Pop == "SQ3"   ~ 0,
      Pop == "TM2"   ~ 0,
      Pop == "WL1"   ~ 0,
      Pop == "WL2"   ~ 0,
      Pop == "WL3"   ~ 0,
      Pop == "YOSE1" ~ 0,
      TRUE ~ 0
    ),
    y = mean_proportion + case_when(
      Pop == "BH"    ~ 0.07,
      Pop == "DPR"   ~ 0.04,
      Pop == "IH"    ~ 0.07,
      Pop == "LV2"   ~ 0.06,
      Pop == "SC"    ~ 0.06,
      Pop == "SQ3"   ~ 0.08,
      Pop == "TM2"   ~ 0.05,
      Pop == "WL1"   ~ -0.07,
      Pop == "WL2"   ~ -0.06,
      Pop == "WL3"   ~ 0.06,
      Pop == "YOSE1" ~ 0.06,
      TRUE ~ 0
    ),
    label = Pop
  ),
  size = 2.5
) +
  scale_y_continuous(expand = c(0, 0.04)) +
  scale_x_continuous(n.breaks = 7) +
  theme_classic() +
  labs(
    x = "Recent Environmental Variability (1995-2025)",
    y = "Proportion Viable"
  )
print(figure_envi_recent)
```

```{r}
figure_envi_historic <- ggplot(pop_envi_historic, aes (x = envi_vari, y = mean_proportion)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin= mean_proportion - SE, ymax = mean_proportion + SE), width = 0.01) +
  geom_text(aes(label = Pop), vjust = -4.8) +
  geom_line(data = prediction_envi_historic, aes(x = envi_vari, y = predicted), inherit.aes = FALSE, color = "red", linewidth = 1) +
  scale_y_continuous(expand = c(0, 0.04)) +
  scale_x_continuous(n.breaks = 7) +
  theme_classic() +
  labs(
    x = "Historic Environmental Variability (1965-1994)",
    y = "Proportion Viable"
  )
print(figure_envi_historic)
```