---
title: "Data_prep_geo_distance"
output: html_document
date: "2026-08-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("geosphere")
```

```{r}
library(dplyr)
library(geosphere)
```

```{r}
coordinate <- read.csv("../input/Sites_coordinate_data.csv")
```

```{r}
CP2 <- coordinate %>%
  filter(Pop == "CP2") %>%
  select(Longitude, Latitude)

coordinate <- coordinate %>%
  mutate (
    distance_km = distHaversine(
      cbind(Longitude, Latitude),
      c(CP2$Longitude, CP2$Latitude)
    )/1000
  )
coordinate
```

```{r}
cp2_elev <- distance %>%
  filter(Pop == "CP2") %>%
  pull(Elev_m)
print(cp2_elev)
elev_distance <- distance %>%
  mutate(
    elev_diff = abs(Elev_m - cp2_elev)
  )
print(elev_distance)
```

```{r}
coordinate <- coordinate %>%
  select(c("Pop", "Elev_m", "Elev_class", "distance_km"))
#write_csv(coordinate, "../output/CP2_Y1_sites_w_distance_km.csv")
```
```{r}
coordinate <- coordinate %>%
  left_join (
    elev_distance %>%
      select (Pop, elev_diff), by = "Pop"
  )
write_csv(coordinate, "../output/CP2_Y1_sites_w_distance_km.csv")
```


