---
output:
  pdf_document: default
  html_document: default
---
```{r}
#lookup table
library(tidyverse)
elevation_df <- tibble(
  Pop = c("TM2","BH","SC","WL1","WL2","WL3","DPR","IH","YOSE1","LV2","SQ3"),
  Elev_m = c(379, 511, 422, 1614, 2020, 2138, 1019, 454, 2141, 2500, 2373)
)

#join data
seed_data <- read.csv("../data/STTO Viability Data - CP2_Y1_Rep1-10_viability_data.csv")
seed_data <- seed_data %>%
  left_join(elevation_df, by = "Pop")

#order population based on ascending elevation
pop_order <- elevation_df %>%
  arrange(Elev_m) %>%
  pull(Pop)
seed_data <- seed_data %>%
  mutate(Pop=factor(Pop,levels=pop_order))
```

```{r}
#check whether Rep is integer and viability category is number
seed_data <- seed_data %>%
  mutate(Rep=as.integer(Rep), Viability_category=as.numeric(Viability_category))
```

# Replicate Summary
```{r}
# Definition1: Category 1 only viable
rep_summary_1 <- seed_data %>%
  group_by(Pop, Elev_m, Rep) %>%
  summarise(
    trials = sum(!is.na(Viability_category)), #check whether there is not NA
    events = sum(Viability_category == 1, na.rm = TRUE), #check how many category 1 seeds in the rep
    .groups = "drop" #cancel group after summarise finished
  ) %>%
  filter (trials >0) %>% #delete no data group
  mutate(proportion = events/trials)
```

```{r}
# Definition 2: Category 1+2  viable
rep_summary_12 <- seed_data %>%
  group_by(Pop, Elev_m, Rep) %>%
  summarise(
    trials = sum(!is.na(Viability_category)), #check whether there is not NA
    events = sum(Viability_category %in% c(1, 2), na.rm = TRUE), #check whether each viability category are 1 or 2
    .groups = "drop" #cancel group after summarise finished
  ) %>%
  filter (trials >0) %>% #delete no data group
  mutate(proportion = events/trials)
```

```{r}
# Definition 3: Category 1+2+3  viable
rep_summary_123 <- seed_data %>%
  group_by(Pop, Elev_m, Rep) %>%
  summarise(
    trials = sum(!is.na(Viability_category)), #check whether there is not NA
    events = sum(Viability_category %in% c(1, 2, 3), na.rm = TRUE), #check whether each viability category are 1 or 2 or 3
    .groups = "drop" #cancel group after summarise finished
  ) %>%
  filter (trials >0) %>% #delete no data group
  mutate(proportion = events/trials)
```

# Population summary

```{r}
#Definition 1
population_summary_1 <- rep_summary_1 %>%
group_by(Pop, Elev_m) %>% #group replicates by population
  summarise( #summarize each population
    n_reps = n(), #number of rep groups
    mean_proportion = mean(proportion), #mean viable proportion
    SE = sd(proportion)/sqrt(n()), #standard error of the mean
    .groups = "drop"
  ) %>%
  arrange(Elev_m) #order populations by elevation
```

```{r}
#Definition 2
population_summary_12 <- rep_summary_12 %>%
group_by(Pop, Elev_m) %>%
  summarise(
    n_reps = n(),
    mean_proportion = mean(proportion),
    SE = sd(proportion)/sqrt(n()),
    .groups = "drop"
  )%>%
  arrange(Elev_m)
```

```{r}
#Definition 3
population_summary_123 <- rep_summary_123 %>%
group_by(Pop, Elev_m) %>%
  summarise(
    n_reps = n(),
    mean_proportion = mean(proportion),
    SE = sd(proportion)/sqrt(n()),
    .groups = "drop"
  )%>%
  arrange(Elev_m)
```

# Linear Regression

```{r}
#Definition 1
lm_1 <- lm( #fit a linear regression model
  proportion ~ Elev_m, #test whether viability changes by elevation
  data = rep_summary_1 #use rep level data
)
```

```{r}
#Definition 2
lm_12 <- lm( #fit a linear regression model
  proportion ~ Elev_m, #test whether viability changes by elevation
  data = rep_summary_12 #use rep level data
)
```

```{r}
#Definition 3
lm_123 <- lm( #fit a linear regression model
  proportion ~ Elev_m, #test whether viability changes by elevation
  data = rep_summary_123 #use rep level data
)
```

# Binomial Logistic Regression

```{r}
#Definition 1
glm_1 <- glm( #fit a binomial logistic regression model
  cbind(events, trials - events) ~ Elev_m, #model viable and non-viable seeds as a function of elevation
  family = binomial, #use binomial error distribution
  data = rep_summary_1 #use rep level summary data
)
```

```{r}
#Definition 2
glm_12 <- glm(
  cbind(events, trials - events) ~ Elev_m,
  family = binomial,
  data = rep_summary_12
)
```

```{r}
#Definition 3
glm_123 <- glm(
  cbind(events, trials - events) ~ Elev_m,
  family = binomial,
  data = rep_summary_123
)
```

# Prediction Data

```{r}
#Definition 1
prediction_1 <- data.frame( #create a new dataset for prediction
  Elev_m = seq( #generate a sequence of elevations
    min(rep_summary_1$Elev_m), #lowest elevation
    max(rep_summary_1$Elev_m), #highest elevation
    length.out = 100 #create 100 evenly spaced values
  )
)
```

```{r}
#Definition 2
prediction_12 <- data.frame(
  Elev_m = seq(
    min(rep_summary_12$Elev_m),
    max(rep_summary_12$Elev_m),
    length.out = 100
  )
)
```

```{r}
#Definition 3
prediction_123 <- data.frame(
  Elev_m = seq(
    min(rep_summary_123$Elev_m),
    max(rep_summary_123$Elev_m),
    length.out = 100
  )
)
```

# Prediction Model

```{r}
#Definition 1
prediction_1$predicted <- predict( #predict viability from the fitted model
  glm_1, #use the belonged logistic model
  newdata = prediction_1, #predict at each elevation
  type = "response" #return predicted probabilities
)
```

```{r}
#Definition 2
prediction_12$predicted <- predict(
  glm_12,
  newdata = prediction_12,
  type = "response"
)
```

```{r}
#Definition 3
prediction_123$predicted <- predict(
  glm_123,
  newdata = prediction_123,
  type = "response"
)
```

# Plots

```{r}
#Definition 1
figure_1 <- ggplot(population_summary_1, aes (x = Elev_m, y = mean_proportion)) + 
  geom_point(size = 3) + #population mean
  geom_errorbar(
    aes(
      ymin = mean_proportion - SE,
      ymax = mean_proportion + SE
    ),
    width = 40
  ) + #standard error
  geom_line( #predicted trendline
    data = prediction_1,
    aes(x=Elev_m, y = predicted),
    linewidth = 1, color = "red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 5,
    size = 3
  ) +
  scale_x_continuous( #x-axis range
    breaks = seq(250, 2500, by = 200),
    limits = c(300, 2600)
  ) +
  scale_y_continuous( #y-axis range
    limits = c(0,1)
  ) +
  theme_classic() + 
  labs(
    x = "Elevation (m)",
    y = "Proportion Viable"
  )
```

```{r}
#Definition 2
figure_12 <- ggplot(population_summary_12, aes (x = Elev_m, y = mean_proportion)) + 
  geom_point(size = 3) + #population mean
  geom_errorbar(
    aes(
      ymin = mean_proportion - SE,
      ymax = mean_proportion + SE
    ),
    width = 40
  ) + #standard error
  geom_line( #predicted trendline
    data = prediction_12,
    aes(x=Elev_m, y = predicted),
    linewidth = 1, color = "red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 5,
    size = 3
  ) +
  scale_x_continuous( #x-axis range
    breaks = seq(250, 2500, by = 200),
    limits = c(300, 2600)
  ) +
  scale_y_continuous( #y-axis range
    limits = c(0,1)
  ) +
  theme_classic() + 
  labs(
    x = "Elevation (m)",
    y = "Proportion Viable"
  )
```

```{r}
#Definition 3
figure_123 <- ggplot(population_summary_123, aes (x = Elev_m, y = mean_proportion)) + 
  geom_point(size = 3) + #population mean
  geom_errorbar(
    aes(
      ymin = mean_proportion - SE,
      ymax = mean_proportion + SE
    ),
    width = 40
  ) + #standard error
  geom_line( #predicted trendline
    data = prediction_123,
    aes(x=Elev_m, y = predicted),
    linewidth = 1, color = "red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 5,
    size = 3
  ) +
  scale_x_continuous( #x-axis range
    breaks = seq(250, 2500, by = 200),
    limits = c(300, 2600)
  ) +
  scale_y_continuous( #y-axis range
    limits = c(0,1)
  ) +
  theme_classic() + 
  labs(
    x = "Elevation (m)",
    y = "Proportion Viable"
  )
```

# Outputs

```{r}
#Definition 1
##Population Summary
print(population_summary_1)
##Linear Regression
print(summary(lm_1))
##Binomial Logistic Regression
print(summary(glm_1))
##Figure
print(figure_1)
```

```{r}
#Definition 2
##Population Summary
print(population_summary_12)
##Linear Regression
print(summary(lm_12))
##Binomial Logistic Regression
print(summary(glm_12))
##Figure
print(figure_12)
```

```{r}
#Definition 3
##Population Summary
print(population_summary_123)
##Linear Regression
print(summary(lm_123))
##Binomial Logistic Regression
print(summary(glm_123))
##Figure
print(figure_123)
```