---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(tidyverse) 
elevation_df <- tibble( #lookup table
  Pop = c("TM2","BH","SC","WL1","WL2","WL3","DPR","IH","YOSE1","LV2","SQ3"),
  Elev_m = c(379, 511, 422, 1614, 2020, 2138, 1019, 454, 2141, 2500, 2373)
)

control_data <- read.csv(
  "../data/STTO Viability Data - Y1_Control_lab_stored_seed_viability_data.csv"
)
control_data <- control_data %>%
  left_join(elevation_df, by = "Pop") #join elevation with population

pop_order <- elevation_df %>%
  arrange(Elev_m) %>% #sort elevation by ascending order
  pull(Pop) #extract population in elevation order

control_data <- control_data %>%
  mutate(
    Pop = factor(Pop, levels = pop_order), #order populations by ascending elevation
    Viability_category = as.numeric(Viability_category)
  )
```

```{r}
control_1 <- control_data %>%
  mutate(
    viable = if_else(
      Viability_category == 1, #assign 1 (viable), 0 (non-viable) based on viability category
      1, #viable
      0 #non-viable
    )
  )
  
control_12 <- control_data %>%
  mutate(
    viable = if_else(
      Viability_category %in% c(1, 2), #assign 1 (viable), 0 (non-viable) based on viability category
      1, #viable
      0 #non-viable
    )
  )
  
control_123 <- control_data %>%
  mutate(
    viable = if_else(
      Viability_category %in% c(1, 2, 3), #assign 1 (viable), 0 (non-viable) based on viability category
      1, #viable
      0 #non-viable
    )
  )
```

```{r}
population_summary_control_1 <- control_1 %>% #group seeds by population
  group_by(Pop, Elev_m) %>%
  summarise (
    n_seeds = n(), #number of control seeds
    mean_proportion = mean(viable), #mean viable
    SE = sd(viable)/sqrt(n()), #SE of mean
    .groups = "drop"
  ) %>%
  arrange(Elev_m) #order population by elevation

population_summary_control_12 <- control_12 %>%
  group_by(Pop, Elev_m) %>%
  summarise (
    n_seeds = n(),
    mean_proportion = mean(viable),
    SE = sd(viable)/sqrt(n()),
    .groups = "drop"
  ) %>%
  arrange(Elev_m)

population_summary_control_123 <- control_123 %>%
  group_by(Pop, Elev_m) %>%
  summarise (
    n_seeds = n(),
    mean_proportion = mean(viable),
    SE = sd(viable)/sqrt(n()),
    .groups = "drop"
  ) %>%
  arrange(Elev_m)

print(population_summary_control_1)
print(population_summary_control_12)
print(population_summary_control_123)
```

```{r}
control_summary_1 <- control_1 %>%
  group_by(Pop, Elev_m) %>% #group seeds by population
  summarise (
    trials = n(), #total number of seeds
    events = sum(viable), #total number of viable seeds
    proportion = events / trials, #proportion of viable
    .groups = "drop"
  ) %>%
  arrange (Elev_m)

control_summary_12 <- control_12 %>%
  group_by(Pop, Elev_m) %>% #group seeds by population
  summarise (
    trials = n(), #total number of seeds
    events = sum(viable), #total number of viable seeds
    proportion = events / trials, #proportion of viable
    .groups = "drop"
  ) %>%
  arrange (Elev_m)

control_summary_123 <- control_123 %>%
  group_by(Pop, Elev_m) %>% #group seeds by population
  summarise (
    trials = n(), #total number of seeds
    events = sum(viable), #total number of viable seeds
    proportion = events / trials, #proportion of viable
    .groups = "drop"
  ) %>%
  arrange (Elev_m)

print(control_summary_1)
print(control_summary_12)
print(control_summary_123)
```

```{r}
lm_control_1 <- lm( #fit linear regression model
  proportion ~ Elev_m, #model viability proportion as a function of elevation
  data = control_summary_1 #use population summary data
)

lm_control_12 <- lm( #fit linear regression model
  proportion ~ Elev_m, #model viability proportion as a function of elevation
  data = control_summary_12 #use population summary data
)

lm_control_123 <- lm( #fit linear regression model
  proportion ~ Elev_m, #model viability proportion as a function of elevation
  data = control_summary_123 #use population summary data
)

print(summary(lm_control_1))
print(summary(lm_control_12))
print(summary(lm_control_123))
```

```{r}
glm_control_1 <- glm( #fit binomial logistic regression model
  viable ~ Elev_m, #model seed viability as function of elevation
  family = binomial, #use binomial error distribution
  data = control_1 #use individual control seed
)

glm_control_12 <- glm( #fit binomial logistic regression model
  viable ~ Elev_m, #model seed viability as function of elevation
  family = binomial, #use binomial error distribution
  data = control_12 #use individual control seed
)

glm_control_123 <- glm( #fit binomial logistic regression model
  viable ~ Elev_m, #model seed viability as function of elevation
  family = binomial, #use binomial error distribution
  data = control_123 #use individual control seed
)

print(summary(glm_control_1))
print(summary(glm_control_12))
print(summary(glm_control_123))
```

```{r}
prediction_control_1 <- data.frame(
  Elev_m = seq( #sequence of elevation
    min(control_summary_1$Elev_m), #low elev
    max(control_summary_1$Elev_m), #high elev
    length.out = 100 #100 even spaced value
  )
)
prediction_control_1$predicted <- predict( 
  glm_control_1, #fitted glm
  newdata = prediction_control_1, #predict across elevation
  type = "response" #return probabilities
)

prediction_control_12 <- data.frame(
  Elev_m = seq( #sequence of elevation
    min(control_summary_12$Elev_m), #low elev
    max(control_summary_12$Elev_m), #high elev
    length.out = 100 #100 even spaced value
  )
)
prediction_control_12$predicted <- predict(
  glm_control_12,
  newdata = prediction_control_12,
  type = "response"
)

prediction_control_123 <- data.frame(
  Elev_m = seq( #sequence of elevation
    min(control_summary_123$Elev_m), #low elev
    max(control_summary_123$Elev_m), #high elev
    length.out = 100 #100 even spaced value
  )
)
prediction_control_123$predicted <- predict(
  glm_control_123,
  newdata = prediction_control_123,
  type = "response"
)
```

```{r}
figure_control_1 <- ggplot(
  population_summary_control_1,
  aes(x = Elev_m, y = mean_proportion)
) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(
      ymin= mean_proportion - SE,
      ymax = mean_proportion +SE
    ),
    width = 40
  ) +
  geom_line(
    data = prediction_control_1,
    aes (x = Elev_m, y = predicted),
    linewidth = 1, color ="red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 10,
    size = 3
  ) +
  theme_classic () +
  labs (
    x = "Elevation (m)",
    y = "Proportion Viable"
  )

figure_control_12 <- ggplot(
  population_summary_control_12,
  aes(x = Elev_m, y = mean_proportion)
) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(
      ymin= mean_proportion - SE,
      ymax = mean_proportion +SE
    ),
    width = 40
  ) +
  geom_line(
    data = prediction_control_12,
    aes (x = Elev_m, y = predicted),
    linewidth = 1, color ="red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 10,
    size = 3
  ) +
  theme_classic () +
  labs (
    x = "Elevation (m)",
    y = "Proportion Viable"
  )

figure_control_123 <- ggplot(
  population_summary_control_123,
  aes(x = Elev_m, y = mean_proportion)
) +
  geom_point(size = 3) +
  geom_errorbar(
    aes(
      ymin= mean_proportion - SE,
      ymax = mean_proportion +SE
    ),
    width = 40
  ) +
  geom_line(
    data = prediction_control_123,
    aes (x = Elev_m, y = predicted),
    linewidth = 1, color ="red"
  ) +
  geom_text( #each point label
    aes(label = Pop),
    vjust = 10,
    size = 3
  ) +
  theme_classic () +
  labs (
    x = "Elevation (m)",
    y = "Proportion Viable"
  )

print(figure_control_1)
print(figure_control_12)
print(figure_control_123)
```